# Notify Deployment Specialist - Check-In Form Ready
# Version: 1.0
# Created: 01/11/2026 11:58 PM
# Purpose: Script for agents to notify Deployment Specialist when check-in form is ready

param(
    [Parameter(Mandatory=$true)]
    [string]$FixName,
    
    [Parameter(Mandatory=$true)]
    [string]$FormPath,
    
    [Parameter(Mandatory=$true)]
    [string]$AgentName
)

$timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
$notificationPath = "D:\Cursor\TheGenie.ai\Development\DevOpsEcosystemManagement\Monitoring\Server Troubleshooting\CheckInLogs\NOTIFY_$FixName`_$timestamp.txt"

$content = @"
CHECK-IN FORM READY FOR REVIEW

Fix Name: $FixName
Form Location: $FormPath
Agent Name: $AgentName
Submitted Date/Time: $(Get-Date -Format "MM/dd/yyyy hh:mm tt")

Please review and approve before check-in.

---
This notification was automatically generated by NOTIFY_DEPLOYMENT_SPECIALIST_v1.ps1
"@

Set-Content -Path $notificationPath -Value $content

Write-Host ""
Write-Host "=== NOTIFICATION SENT ===" -ForegroundColor Green
Write-Host ""
Write-Host "Fix Name: $FixName" -ForegroundColor Cyan
Write-Host "Form Location: $FormPath" -ForegroundColor Cyan
Write-Host "Agent Name: $AgentName" -ForegroundColor Cyan
Write-Host "Notification File: $notificationPath" -ForegroundColor Yellow
Write-Host ""
Write-Host "✅ Deployment Specialist has been notified." -ForegroundColor Green
Write-Host "⏳ Please wait for approval before checking in code." -ForegroundColor Yellow
Write-Host ""
