-- ============================================================================
-- PLS RESO Engine - PlsListingOwnership Table
-- Version: 3.0
-- Created: 01/05/2026
-- Last Updated: 01/05/2026
-- Author: Cursor AI Agent
-- Purpose: Flexible ownership tracking for PLS listings (supports multiple owners)
-- ============================================================================
--
-- ARCHITECTURE CLARIFICATION:
--   - pls_tracking = Lifecycle/metadata tracking (status, source, flags)
--   - PlsListingOwnership = Ownership tracking (who owns/co-owns listing)
--   - These are SEPARATE concerns - tracking vs ownership
--
-- OWNERSHIP MODEL:
--   - Currently supports max 2 owners (Creator + CoAgent)
--   - Architecture is flexible for future expansion (e.g., different property types)
--   - OwnershipTypeId: 1=Creator, 2=CoAgent (can expand later)
--
-- ============================================================================

USE FarmGenie;
GO

-- ============================================================================
-- TABLE: PlsListingOwnership
-- Purpose: Track user ownership of PLS listings (flexible for multiple owners)
-- ============================================================================

IF OBJECT_ID('dbo.PlsListingOwnership', 'U') IS NOT NULL
    DROP TABLE dbo.PlsListingOwnership;
GO

CREATE TABLE dbo.PlsListingOwnership (
    -- Primary Key
    PlsListingOwnershipId INT IDENTITY(1,1) NOT NULL,
    
    -- Foreign Keys
    AspNetUserId NVARCHAR(128) NOT NULL,
        -- References: FarmGenie.dbo.AspNetUsers(Id)
        -- NOTE: Matches actual database structure (NVARCHAR(128))
    ListingId INT NOT NULL,
        -- References: MlsListing.dbo.Listing(ListingID)
        -- Note: Cross-database FK not enforced, validated in application layer
    
    -- Ownership Metadata
    MlsId INT NOT NULL DEFAULT 777,
        -- PLS identifier (changed from 999 to 777 to match v3.0 schema)
    MlsNumber VARCHAR(10) NOT NULL,
        -- PLS number format: 'PLS{6-digit}{letter}' (e.g., 'PLS100000A')
        -- Generated by usp_GetNextPlsNumber stored procedure
    
    OwnershipTypeId INT NOT NULL DEFAULT 1,
        -- 1 = Creator (primary owner)
        -- 2 = CoAgent (co-owner)
        -- Future: Can expand for different property types or ownership models
    
    -- Status Flags
    IsActive BIT NOT NULL DEFAULT 1,
        -- Soft delete flag
        -- FALSE = ownership record is inactive (listing transferred/deleted)
    
    -- Audit Timestamps
    CreateDate DATETIME2(7) NOT NULL DEFAULT GETUTCDATE(),
    LastUpdate DATETIME2(7) NOT NULL DEFAULT GETUTCDATE(),
    
    -- Constraints
    CONSTRAINT PK_PlsListingOwnership PRIMARY KEY CLUSTERED (PlsListingOwnershipId),
    CONSTRAINT FK_PlsListingOwnership_User FOREIGN KEY (AspNetUserId) 
        REFERENCES dbo.AspNetUsers(Id) ON DELETE CASCADE,
    -- Unique constraint: One ownership record per user per listing per type
    -- This allows: User can be Creator (TypeId=1) AND CoAgent (TypeId=2) on different listings
    -- But prevents: Same user having duplicate ownership of same type on same listing
    CONSTRAINT UQ_PlsListingOwnership_User_Listing_Type UNIQUE (AspNetUserId, ListingId, OwnershipTypeId),
    -- Unique constraint: PLS number uniqueness per user per MLS
    -- Ensures one PLS number per user per MLS (prevents duplicates)
    CONSTRAINT UQ_PlsListingOwnership_User_Mls_Number UNIQUE (AspNetUserId, MlsId, MlsNumber)
);
GO

-- ============================================================================
-- INDEXES
-- ============================================================================

-- Index for listing lookups (most common query: "Who owns this listing?")
CREATE NONCLUSTERED INDEX IX_PlsListingOwnership_ListingId 
    ON dbo.PlsListingOwnership (ListingId, IsActive)
    INCLUDE (AspNetUserId, OwnershipTypeId, MlsNumber);
GO

-- Index for user lookups (common query: "What listings does this user own?")
CREATE NONCLUSTERED INDEX IX_PlsListingOwnership_AspNetUserId 
    ON dbo.PlsListingOwnership (AspNetUserId, IsActive)
    INCLUDE (ListingId, OwnershipTypeId, MlsNumber, MlsId);
GO

-- Index for PLS number lookups (if queried by PLS number)
CREATE NONCLUSTERED INDEX IX_PlsListingOwnership_MlsNumber 
    ON dbo.PlsListingOwnership (MlsNumber, MlsId)
    INCLUDE (AspNetUserId, ListingId, OwnershipTypeId, IsActive);
GO

-- Index for ownership type queries (e.g., "Find all CoAgents")
CREATE NONCLUSTERED INDEX IX_PlsListingOwnership_OwnershipType 
    ON dbo.PlsListingOwnership (OwnershipTypeId, IsActive)
    INCLUDE (AspNetUserId, ListingId, MlsNumber);
GO

-- ============================================================================
-- USAGE EXAMPLES
-- ============================================================================

/*
-- Example 1: Create ownership record for Creator
INSERT INTO dbo.PlsListingOwnership (AspNetUserId, ListingId, MlsId, MlsNumber, OwnershipTypeId)
VALUES ('user-guid-here', 12345, 777, 'PLS-2026-00001', 1);
GO

-- Example 2: Add CoAgent ownership
INSERT INTO dbo.PlsListingOwnership (AspNetUserId, ListingId, MlsId, MlsNumber, OwnershipTypeId)
VALUES ('co-agent-guid-here', 12345, 777, 'PLS-2026-00001', 2);
GO

-- Example 3: Check if user owns a listing (for authorization)
SELECT COUNT(*) AS OwnershipCount
FROM dbo.PlsListingOwnership
WHERE ListingId = 12345
    AND AspNetUserId = 'user-guid-here'
    AND OwnershipTypeId = 1  -- Creator
    AND IsActive = 1;
GO

-- Example 4: Get all owners of a listing
SELECT 
    plo.AspNetUserId,
    u.UserName,
    plo.OwnershipTypeId,
    CASE plo.OwnershipTypeId
        WHEN 1 THEN 'Creator'
        WHEN 2 THEN 'CoAgent'
        ELSE 'Unknown'
    END AS OwnershipTypeName,
    plo.MlsNumber,
    plo.IsActive
FROM dbo.PlsListingOwnership plo
INNER JOIN dbo.AspNetUsers u ON u.Id = plo.AspNetUserId
WHERE plo.ListingId = 12345
    AND plo.IsActive = 1
ORDER BY plo.OwnershipTypeId, plo.CreateDate;
GO

-- Example 5: Get all listings owned by a user
SELECT 
    l.ListingID,
    l.MlsNumber,
    l.DisplayAddress,
    plo.OwnershipTypeId,
    CASE plo.OwnershipTypeId
        WHEN 1 THEN 'Creator'
        WHEN 2 THEN 'CoAgent'
        ELSE 'Unknown'
    END AS OwnershipTypeName,
    plo.MlsNumber AS PlsNumber,  -- Format: PLS100000A
    plo.IsActive
FROM MlsListing.dbo.Listing l
INNER JOIN dbo.PlsListingOwnership plo ON plo.ListingId = l.ListingID
WHERE plo.AspNetUserId = 'user-guid-here'
    AND l.MlsID = 777
    AND plo.IsActive = 1
ORDER BY plo.CreateDate DESC;
GO

-- Example 6: Soft delete ownership (transfer listing)
UPDATE dbo.PlsListingOwnership
SET IsActive = 0,
    LastUpdate = GETUTCDATE()
WHERE ListingId = 12345
    AND AspNetUserId = 'old-owner-guid-here';
GO
*/

-- ============================================================================
-- RELATIONSHIP TO OTHER TABLES
-- ============================================================================
--
-- PlsListingOwnership vs pls_tracking:
--   - PlsListingOwnership = WHO owns the listing (ownership/authorization)
--   - pls_tracking = WHAT is the status/source (lifecycle/metadata)
--   - These are SEPARATE concerns - both needed
--
-- Example: A listing can have:
--   - pls_tracking.agent_id = Primary agent (for lifecycle tracking)
--   - PlsListingOwnership (Creator) = Same agent (for ownership)
--   - PlsListingOwnership (CoAgent) = Different agent (co-owner)
--
-- Future Expansion:
--   - OwnershipTypeId can expand beyond 1,2 for different property types
--   - Architecture supports multiple owners per listing
--   - Current cap: 2 owners (Creator + CoAgent)
--   - Future: Could add OwnershipTypeId 3, 4, etc. for different scenarios
--
-- ============================================================================

PRINT 'PlsListingOwnership table created successfully';
PRINT '';
PRINT 'Key Features:';
PRINT '  - Flexible ownership model (supports multiple owners)';
PRINT '  - Currently supports: Creator (1) + CoAgent (2)';
PRINT '  - Architecture ready for future expansion';
PRINT '  - Separate from pls_tracking (ownership vs lifecycle)';
PRINT '';
PRINT 'Indexes created:';
PRINT '  - IX_PlsListingOwnership_ListingId (listing lookups)';
PRINT '  - IX_PlsListingOwnership_AspNetUserId (user lookups)';
PRINT '  - IX_PlsListingOwnership_MlsNumber (PLS number lookups)';
PRINT '  - IX_PlsListingOwnership_OwnershipType (type queries)';
GO

